spring.application.name=esiusuarios
server.port=8081

#-- Esto es para la conexión a la base de datos SQL Server ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DBUsuarios;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password= --contraseña--
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

#-- JWT --
app.jwt.secret= --clave-secreta--
app.jwt.expiration-ms=86400000

#-- Recuperación de contraseña --
app.reset.expiration-minutes=20

#-- Configuración de correo electrónico --
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= --correo-electrónico--
spring.mail.password= --contraseña-del-correo--
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#direccion de mail que aparece como remitente en los correos de recuperación de contraseña
app.mail.from= --correo-electrónico--